### ISSUE TITLE
Using 5'GEX /TCR libraries

### ISSUE THREAD

**Issue by callumparr** [WGLab/AmpBinner#3]
Would it be possible to use this tool to demultiplex long cDNA reads generated through 5' TSO 10x library generation?

**Comment by fangli08** [comment]
Do you have a cartoon showing the library structure?

**Comment by callumparr** [comment]
<img width="1537" alt="Screen Shot 2021-01-09 at 11 49 56 PM" src="https://user-images.githubusercontent.com/41637575/104095995-47c0cd80-52dd-11eb-9291-c7ca50177bde.png">

Sure. It is 5' GEX amplified library before fragmentation and then end-repair with ligation of the 1D sequencing adapters. cDNA insert should have anchor oligo-dT priming.

**Comment by fangli08** [comment]
Yes. I think `ampBinner_10X.py` should work on the 5' TSO 10x library.

 You can supply this sequence 
![image](https://user-images.githubusercontent.com/9782948/104192867-70d08380-53ed-11eb-86ce-4e7c4b6da820.png)

  to `--barcode_upstream_seq`. 

Please note that `ampBinner_10X.py` wouldn't work well if the supplied barcode list is the complete list of all possible barcodes (a few million), as many of the barcodes have very similar sequences and are indistinguishable given the error rate of the long reads. Usually, only a subset of the barcodes was used in one experiment. So it's better that you narrow down the barcode list as much as you can to improve the accuracy. 

If you encounter any issues, please let me know.

**Comment by callumparr** [comment]
I have a whitelist of barcodes from parallel MiSeq run. Thank you I will give it try and let you know how it goes.

**Comment by fangli08** [comment]
That's great!

**Comment by fangli08** [comment]
Is this issue solved?
