### ISSUE TITLE
Use ampbinner_10X.py on fasta file

### ISSUE THREAD

**Issue by jkbenotmane** [WGLab/AmpBinner#5]
Would it be possible to use the AmpBinner in 10X Mode on .fasta files?

Thank you in Advance!

**Comment by fangli08** [comment]
The quality values in the fastq do not really matter. You can convert the fasta to fastq, just add an arbitrary quality value. 
For example, you can use this seqtk: https://github.com/lh3/seqtk

`seqtk seq -F 0 input.fasta > out.fastq`

It will add '0' as the quality char, which corresponds to quality value 15.

**Comment by jkbenotmane** [comment]
Thank you Really Much, that solved it!
